config/routes.rb
MyWords::Application.routes.draw do

  resources :users

  resources :lists do
    member do
      patch 'clear_words'
    end
    resources :words
  end

  resources :imports, only: [:new, :create, :edit, :update]
  resources :passwords, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]


  root to: 'static_pages#home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/list.rb
class List < ActiveRecord::Base

  MAXWORDS=50
  MAXLISTS=10

  belongs_to :user

  has_many :lists_words
  has_many :words, -> { order(word: :asc) }, through: :lists_words, inverse_of: :lists

  accepts_nested_attributes_for :words

  #Validations
  validates_presence_of :listname
  validates_length_of :listname, maximum: 45, message: "List names should be less than 45 characters"
  validates_uniqueness_of :listname, scope: :user_id, message: "This list name already exists as part of your list collection"
  validate :max_words
  validates_associated :words


  def count_words
    self.words.count
  end

  def words_remaining
    MAXWORDS-count_words
  end

  def to_s
    self.listname
  end

  def self.maxwords
    50
  end

private
  def max_words
    if words.length > MAXWORDS
      self.errors[:base]<< "maximum #{MAXWORDS} words per list"
      false
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include ListsHelper

  before_filter :signed_in_user, only: [:show, :create, :destroy, :clear_words, :import]
  before_filter :list_owner,   only: [:destroy, :update, :clear_words, :import]

  def new
    @list = List.new
  end

  def create
    @list=current_user.lists.build(list_params)
      if @list.save
        redirect_to edit_list_path(@list), flash: { notice: "Successfully created your list."}
      else
        render :edit
      end
  end

  def destroy
    @list.destroy
    redirect_to root_url, flash: { notice: "The list #{@list.to_s} has been deleted" }
  end

  def edit
    @list = List.find(params[:id])
  end

  def show
    @list=List.find(params[:id])
  end

  # TODO: Refractor
  def update
    @list = List.find(params[:id])
    arry_add_words=Array.new

    # Update Listname if change
    unless @list.listname == params[:list][:listname]
      @list.update_attribute(:listname, params[:list][:listname])
    end

    if words_are_unique?
      this_lists_words = params[:list][:words_attributes]

      if this_lists_words.count > List::MAXWORDS
        @list.errors[:base] << "You have to many words in your list"
        render :edit
        return
      else
        @list.words = [] if @list.persisted?
        this_lists_words.each do |k,w|
          the_word = Word.find_or_create_by(word: w[:word])
          arry_add_words << the_word.id
        end
      end

      if @list.word_ids=arry_add_words
          redirect_to edit_list_path(@list), flash: { notice: "Successfully updated your list."}
      else
          # Somthing went wrong with the save
      end

    else
      @list.errors[:base] << "You have duplicate words in this list"
      render :edit
    end
  end

  def clear_words
    @list=List.find(params[:id])
    if @list.words.clear
      redirect_to edit_list_path(@list), flash: { notice: "All words removed" }
    else
      render :edit
    end
  end

 private

  def list_params
    params.require(:list).permit(:id, :listname, :listtype,
     words_attributes:  [ :id, :word ])
  end

  def words_are_unique?
    # Unique words submitted, no double up's in current list
    # Catch before getting to Model.
    word_counts=Hash.new(0)
    nested_words=params[:list][:words_attributes].map { |k,v| v[:word] }
    nested_words.each{ |val| word_counts[val]+=1 }
    word_counts.reject!{ |val, count| count==1 }

    if word_counts.length==0
      return true
    else
      return false
    end
  end

  def list_owner
    unless list_owner?(params[:id])
      flash[:error] = "You must own the list you are modifing"
      redirect_to root_url
    end
  end

end

app/helpers/lists_helper.rb
module ListsHelper

  def list_owner?(listid)
    !current_user.lists.find_by_id(listid).nil?
  end

end

app/views/lists/_word_fields.html.erb
<%= f.text_field :word %>

app/views/lists/edit.html.erb
<% provide(:title, @list.listname) %>

  <%= form_for @list, url: {action: "update" } do |list_details| %>

    <%= render partial: 'shared/validation', object: list_details.object %>

    <div id="list_panel" class="form-group">
      <%= list_details.label :listname %>:
      <%= list_details.text_field :listname ,class: "form-control" %>
    </div>

    <div id="words_panel" class="form-group">
      <%= list_details.fields_for :words do |list_words| %>
        <%= render 'word_fields', f: list_words %>
      <% end %>
    </div>

    <div id="actions" class="btn-toolbar">
      <div class="btn-group  btn-group-sm">
        <div class="btn btn-default">
          <%= link_to_add_fields "Add Word", list_details, :words %>
        </div>
        <%= link_to "Import Words", new_import_path(list_id: @list.id), class: "btn btn-default" %>
        <%= link_to "Print List", '#', onclick: "printpage()", class: "btn btn-default" %>
      </div>

      <div class="btn-group  btn-group-sm">
        <%= list_details.submit "Save Changes", class: "btn btn-primary " %>
        <%= link_to "Clear words", clear_words_list_path(@list), method: :patch, data: { confirm: "Re you sure?" }, class: "btn btn-danger" %>
        <%= link_to "Delete List", @list, method: :delete,
      data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      </div>

    </div>
  <% end %>

app/views/lists/new.html.erb
<% provide(:title, 'New List') %>
<h1>Add List</h1>

    <%= form_for(@list) do |list| %>
    <%= render partial: 'shared/validation', object: list.object %>

      <%= list.label :listname, 'List Name' %>
      <%= list.text_field :listname %>
      <br />
      <%= list.label :listtype, 'List Type' %>
      <%= list.select(:listtype, [['Personel','u'], ['School', 's'], ['Free','f']]) %>
      <br />
      <div class="btn-group-sm">
        <%= list.submit "Create List", class: "btn btn-primary" %>
      </div>

    <% end %>