config/routes.rb
MyWords::Application.routes.draw do

  resources :users

  resources :lists do
    member do
      patch 'clear_words'
    end
    resources :words
  end

  resources :imports, only: [:new, :create, :edit, :update]
  resources :passwords, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]


  root to: 'static_pages#home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/import.rb
class Import
include ActiveModel::Model

  attr_accessor :file, :list_id

  def initialize(attributes = {})
      attributes.each { |name, value| send("#{name}=", value) }
  end

##Have Removed the persisted method. Not needed I beleive

  def save
    if load_imported_lists(1)
      true
    else
      false
    end
  end

  def load_imported_lists(list_num)
    @spreadsheet = open_spreadsheet
    @list=List.find_by_id(list_id) || List.new

    arry_import_words=words_in_list(list_num)
    arry_original_list_words=@list.word_ids
    arry_new_list_words = arry_import_words | arry_original_list_words

    if arry_new_list_words.count <= List::MAXWORDS
      if @list.word_ids=arry_new_list_words
        true
      else
        # Raise an exception - somthing went wrong with the save
      end
    else
      self.errors[:base] << "The list #{@list.listname} exceeds the maximum of words #{List::MAXWORDS} allowed."
      false
    end
  end

  def number_of_lists
    @spreadsheet.last_column > List::MAXLISTS ? List::MAXLISTS : @spreadsheet.last_column
  end

  def words_in_list(col_num)
    import_ids=[]
    (2..@spreadsheet.last_row).each do |row_num|
      unless @spreadsheet.cell(row_num, col_num) == ""
          word=Word.find_or_create_by(word: @spreadsheet.cell(row_num, col_num))
        unless import_ids.include?(word.id)
          import_ids << word.id
        else
          self.errors[:base] << "The word #{word.word} is included multiple times in your list, it was skipped."
        end
      end
    end
    import_ids
  end

  def open_spreadsheet
    case File.extname(file.original_filename)
      when ".ods" then Roo::OpenOffice.new(file.path, nil, :ignore)
      when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else
      raise "Unknown file type: #{file.original_filename}"
    end
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  include ListsHelper

  before_filter :signed_in_user, only: [:new, :create]
  before_filter :list_owner, only: [:edit, :update]

  def new

  end

  def create

  end

  def edit
    @list=List.find(params[:list_id]) if params[:list_id].present?
    @import_form = ImportForm.new
  end

  def udate
    @import_form = ImportForm.new(import_list_params)
    @list=List.find(@import_lists.list_id)
    if @import_form.save
      redirect_to edit_list_path(@list), flash: { notice: "Imported list successfully."}
    else
      render :new
     end
  end

private

  def list_owner
    if params[:list_id].present?
      unless list_owner?(params[:list_id])
        flash[:error] = "You must own the list you are importing into"
        redirect_to root_url
      end
    end
  end


  def import_list_params
    params.require(:import_form).permit(:file, :list_id
      )
  end
end

app/views/imports/edit.html.erb
<h1>Import words <%= @list.listname if @list.present?  %></h1>

<p>
  A CSV, Excel or Open Document Speadsheet can be used to import words into your list. You are allowed to import up to <%= List.maxwords %> words per list. You have <%= @list.words_remaining if @list.present? %> remaining in this list.
</p>

<ul>
       <li>
        <strong>Word Format</strong> -
        upto  characters with no spaces.
      </li>
      <li>
        <strong>Duplicates</strong> - There should be no duplicate words in your list.
      </li>
      <li>
        <strong>Capitalisation will be maintained</strong> - There is no easy way for us to determine capitalisation, you will need to do this.
      </li>
</ul>

<%= form_for @import_form, url: imports_path, method: :post  do |f| %>
  <% if @import_form.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@import_form.errors.count, "error") %> prohibited this import from completing:</h2>
      <ul>
        <% @import_form.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <%= f.file_field :file %>
  </div>

  <% if @list.present? %>
    <%= f.hidden_field :list_id, value: @list.id  %>
  <% end %>

  <div class="buttons">
    <%= f.submit "Import" %>
  </div>

<% end %>

app/views/imports/new.html.erb
<h1>Import words <%= @list.listname if @list.present?  %></h1>

<p>
  A CSV, Excel or Open Document Speadsheet can be used to import words into your list. You are allowed to import up to <%= List.maxwords %> words per list. You have <%= @list.words_remaining if @list.present? %> remaining in this list.
</p>

<ul>
       <li>
        <strong>Word Format</strong> -
        upto  characters with no spaces.
      </li>
      <li>
        <strong>Duplicates</strong> - There should be no duplicate words in your list.
      </li>
      <li>
        <strong>Capitalisation will be maintained</strong> - There is no easy way for us to determine capitalisation, you will need to do this.
      </li>
</ul>

<%= form_for @import_lists  do |f| %>
  <% if @import_lists.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@import_lists.errors.count, "error") %> prohibited this import from completing:</h2>
      <ul>
        <% @import_lists.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <%= f.file_field :file %>
  </div>

  <% if @list.present? %>
    <%= f.hidden_field :list_id, value: @list.id  %>
  <% end %>

  <div class="buttons">
    <%= f.submit "Import" %>
  </div>

<% end %>