config/routes.rb
MyWords::Application.routes.draw do

  resources :users

  resources :lists do
    member do
      patch 'clear_words'
    end
    resources :words
  end

  resources :imports, only: [:new, :create, :edit, :update]
  resources :passwords, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]


  root to: 'static_pages#home'

  get '/help',    to: 'static_pages#help'
  get '/about',   to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'

  get '/signup',  to: 'users#new'
  get '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_footer.html.erb
<footer>
  <small> &copy Commercial Applications pty. ltd.</small>
  <nav class = "navbar" role="navigation">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contacts", contacts_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "row">

  <div class="page-header">
    <h1>Scholastic Software</h1>
  </div>

    <nav id="nav_bar_top" class="navbar navbar-default navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#dropdown">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Drop Down Menu Creation -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path, class: "navbar-brand" %></li>
          <li><%= link_to "Help", help_path, class: "navbar-brand" %></li>

          <li class= "dropdown" >
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              File <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Import", new_import_path %></li>
              <li><%= link_to "Export", "#" %></li>

            </ul>
          </li>

          <% if signed_in? %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              MyLists <b class="caret"></b>
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View" %></li>
                <li><%= link_to "New", new_list_path(current_user) %></li>
              </ul>
            </li>
          <% end %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <% if signed_in? %>
              <li><%= link_to "My Profile", current_user %></li>
              <li><%= link_to "My Details", edit_user_path(current_user) %></li>
              <li><%= link_to "My Password Change", new_password_path %></li>
              <li><%= link_to "MyWords Users", users_path if current_user.admin? %>
              <li class="divider"></li>
              <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
            </ul>
          </li>

        </ul>
      </div>

    </nav>
</header>

app/views/layouts/_lhmenu.html.erb
<aside>
<div class ="navbar-left">
    <ul class="nav nav-tabs nav-stacked">
      <li class="nav-header">Free Lists</li>
      <li><a href="#">Dolch</a></li>
      <li><a href="#">Top 100</a></li>
      <li><a href="#">Red Sight Words</a></li>
      <li><a href="#">Blue Sight Words</a></li>

  <% if signed_in? %>
    <li class="nav-header">My Lists</li>
    <% current_user.my_lists("u").each do |list| %>
      <li><%= link_to list.listname, edit_list_path(list.id) %>
      </li>
    <% end %>

    <li class="nav-header">My Schools Lists</li>
    <% current_user.my_lists("s").each do |list| %>
        <li><%= link_to list.listname, edit_list_path(list.id) %>
        </li>
    <% end %>
    </ul>
  <% end %>
</div>
</aside>

app/views/layouts/_lists.html.erb
<div id="LHM" class ="pull-left">
    <ul class="nav nav-list">
      <li class="nav-header">Free Lists</li>
      <li><a href="#">Dolch</a></li>
      <li><a href="#">Top 100</a></li>
      <li><a href="#">Red Sight Words</a></li>
      <li><a href="#">Blue Sight Words</a></li>
    <li class="nav-header">My Lists</li>
    <% if signed_in? %>
      <%= render 'lists/userlists' %>
    <% else %>
    <li><a href="#">sign in?</a>
    <% end %>
    <li class="nav-header">My Schools Lists</li>
    <% if signed_in? %>
    <% else %>
    <li><a href="#">sign-in?</a>
    <% end %>
    </ul>
  </div>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <%= render 'layouts/shim' %>
  <div class="container">

  <div id="heading" class = "row">
    <div class="col-md-12">
      <%= render 'layouts/header' %>
    </div>
  </div>

  <div class="row">
    <div id="nav_left" class="col-md-2">
      <%= render 'layouts/lhmenu' %>
    </div>

    <div id="main_panel" class="col-md-10">
      <%= render partial: "shared/flash_messages", flash: flash %>
      <%= yield %>
    </div>

    <div class="row">
      <div id="footer" class = "col-md-12">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </div>

</body>
</html>